checks:
    python:
        code_rating: true
        duplicate_code: true
tools:
    pylint:
        python_version: '3'
        config_file: 'ci/pylint-scrutinizer.rc'
filter:
    excluded_paths:
        - '*/migrations/*'
before_commands:
    - sudo pip install -r ci/requirements-scrutinizer.txt
    - sudo pip3 install -r ci/requirements-scrutinizer.txt
build:
    environment:
        python: 3.6
    dependencies:
        override:
            - pip install six
            - pip install -r ci/requirements-scrutinizer.txt
    tests:
        override:
            -
                command: ./manage.py collectstatic --settings=weblate.settings_test --noinput
            -
                command: coverage run --source . ./manage.py test --settings=weblate.settings_test
            -
                command: coverage combine
                coverage:
                    file: .coverage
                    format: py-cc
